name: first workflow
on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggers
jobs:
  echoing:
    runs-on: ubuntu-latest
    steps:
      - name: "23f2000573@ds.study.iitm.ac.in"
        run: |
          echo "This is my first actions workflow. This is done for TDS week-2 question 7" >> abc.txt
          git add abc.txt
          git commit -m "Update" || echo "No changes to commit"
          git push origin main
