name: first workflow
on:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  echoing:
    runs-on: ubuntu-latest
    steps:
      - name: "23f2000573@ds.study.iitm.ac.in"
        run: |
          echo "This is my first actions workflow. This is done for TDS week-2 question 7" >> abc.txt
          git add abc.txt
          git commit -m "Update" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Uses GitHub's built-in authentication
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git push origin main

